# Generated by Django 3.2 on 2022-08-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnkenList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keiriShonin', models.BooleanField()),
                ('statusCode', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('edabanGroup', models.IntegerField()),
                ('shiharaiPattern', models.IntegerField()),
                ('kanriNo', models.CharField(max_length=30)),
                ('edaban', models.CharField(max_length=30)),
                ('ankenMei', models.CharField(max_length=30)),
                ('torihikisakiCode', models.IntegerField()),
                ('torihikisakiMei', models.CharField(max_length=30)),
                ('kanjokamoku', models.CharField(max_length=30)),
                ('keikakuTanka', models.IntegerField()),
                ('keikakuSuu', models.IntegerField()),
                ('keikakuGokei', models.IntegerField()),
                ('mitsumoriTanka', models.IntegerField()),
                ('mitsumoriSuu', models.IntegerField()),
                ('mitsumoriGokei', models.IntegerField()),
                ('mitsumoriLink', models.URLField()),
                ('wfNo', models.CharField(max_length=30)),
                ('keiyakuKingaku', models.IntegerField()),
                ('chumonTanka', models.IntegerField()),
                ('chumonSuu', models.IntegerField()),
                ('chumonGokei', models.IntegerField()),
                ('chumonLink', models.URLField()),
                ('nohinTanka', models.IntegerField()),
                ('nohinSuu', models.IntegerField()),
                ('nohinGokei', models.IntegerField()),
                ('shiharaiTanka', models.IntegerField()),
                ('konyuSuu', models.IntegerField()),
                ('konyuGokei', models.IntegerField()),
                ('seikyushoLink', models.URLField()),
                ('keikaku_Jisseki', models.IntegerField()),
                ('nohinKigen', models.DateTimeField()),
                ('kenshuKigen', models.DateTimeField()),
                ('shiharaiKigen', models.DateTimeField()),
                ('kurikaeshiKigen', models.DateTimeField()),
                ('ringishoLink', models.URLField()),
                ('keiyakushoLink', models.URLField()),
                ('konyuKaisha', models.CharField(max_length=30)),
                ('dataKoshinbi', models.DateTimeField()),
                ('saishuKoshinsha', models.CharField(max_length=30)),
                ('shainNo', models.IntegerField()),
                ('tantosha', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ankenList',
            },
        ),
    ]
