# Generated by Django 3.2 on 2022-08-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankenlist',
            name='chumonGokei',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='chumonLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='comment',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='dataKoshinbi',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='edaban',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='edabanGroup',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keiyakushoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='konyuKaisha',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='mitsumoriGokei',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='nohinGokei',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='ringishoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='saishuKoshinsha',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='seikyushoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='shainNo',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='tantosha',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='torihikisakiCode',
            field=models.IntegerField(blank=True),
        ),
    ]
