# Generated by Django 3.2 on 2022-08-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220810_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ankenlist',
            name='edabanGroup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keikakuSuu',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keikaku_Jisseki',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keiriShonin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keiyakuKingaku',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='mitsumoriLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='wfNo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
