# Generated by Django 3.2 on 2022-08-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220810_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankenlist',
            name='statusCode',
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='keiyakushoNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='nohinLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='onatsuRingiLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='onatsuRingiNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='ringiGokei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='ringiSuu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='ringiTanka',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ankenlist',
            name='ringishoNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='ankenMei',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='chumonGokei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='chumonLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='chumonSuu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='chumonTanka',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='dataKoshinbi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='edaban',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='kanjokamoku',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='kanriNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keikakuGokei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keikakuSuu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keikakuTanka',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keikaku_Jisseki',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keiriShonin',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keiyakuKingaku',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='keiyakushoLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='kenshuKigen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='konyuGokei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='konyuKaisha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='konyuSuu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='kurikaeshiKigen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='mitsumoriGokei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='mitsumoriLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='mitsumoriSuu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='mitsumoriTanka',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='nohinGokei',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='nohinKigen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='nohinSuu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='nohinTanka',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='ringishoLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='saishuKoshinsha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='seikyushoLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='shainNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='shiharaiKigen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='shiharaiPattern',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='shiharaiTanka',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='tantosha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='torihikisakiCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='torihikisakiMei',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ankenlist',
            name='wfNo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
