# Generated by Django 3.2 on 2022-08-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220817_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankenlist',
            name='statusCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
